classdef AcceptedAudiences < adx.control.JSONMapper
% AcceptedAudiences Represents an accepted audience trusted by the cluster.
% 
% AcceptedAudiences Properties:
%   value - GUID or valid URL representing an accepted audience. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % value - GUID or valid URL representing an accepted audience. - type: string
        value string { adx.control.JSONMapper.fieldName(value,"value") }
    end

    % Class methods
    methods
        % Constructor
        function obj = AcceptedAudiences(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.AcceptedAudiences
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

