classdef AttachedDatabaseConfiDefaultPrincipalsModificationKindEnum_0000 < adx.control.JSONEnum
% AttachedDatabaseConfiDefaultPrincipalsModificationKindEnum_0000 No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Union ("Union")
        Replace ("Replace")
        None ("None")
    end

end %class

