classdef AzureSku < adx.control.JSONMapper
% AzureSku Azure SKU definition.
% 
% AzureSku Properties:
%   name - SKU name. - type: string
%   capacity - The number of instances of the cluster. - type: int32
%   tier - SKU tier. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % name - SKU name. - type: string
        name adx.control.models.AzureSkuNameEnum { adx.control.JSONMapper.fieldName(name,"name") }
        % capacity - The number of instances of the cluster. - type: int32
        capacity int32 { adx.control.JSONMapper.fieldName(capacity,"capacity") }
        % tier - SKU tier. - type: string
        tier adx.control.models.AzureSkuTierEnum { adx.control.JSONMapper.fieldName(tier,"tier") }
    end

    % Class methods
    methods
        % Constructor
        function obj = AzureSku(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.AzureSku
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

