classdef AzureResourceSku < adx.control.JSONMapper
% AzureResourceSku Azure resource SKU definition.
% 
% AzureResourceSku Properties:
%   resourceType - Resource Namespace and Type. - type: string
%   sku - type: AzureSku
%   capacity - type: AzureCapacity

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % resourceType - Resource Namespace and Type. - type: string
        resourceType string { adx.control.JSONMapper.fieldName(resourceType,"resourceType") }
        % sku - type: AzureSku
        sku adx.control.models.AzureSku { adx.control.JSONMapper.fieldName(sku,"sku") }
        % capacity - type: AzureCapacity
        capacity adx.control.models.AzureCapacity { adx.control.JSONMapper.fieldName(capacity,"capacity") }
    end

    % Class methods
    methods
        % Constructor
        function obj = AzureResourceSku(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.AzureResourceSku
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

