classdef BlobStorageEventType < adx.control.JSONEnum
% BlobStorageEventType The name of blob storage event type to process.

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Microsoft_Storage_BlobCreated ("Microsoft.Storage.BlobCreated")
        Microsoft_Storage_BlobRenamed ("Microsoft.Storage.BlobRenamed")
    end

end %class

