classdef CheckNameRequestTypeEnum < adx.control.JSONEnum
% CheckNameRequestTypeEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Microsoft_Kusto_clusters_databases ("Microsoft.Kusto/clusters/databases")
        Microsoft_Kusto_clusters_attachedDatabaseConfigurations ("Microsoft.Kusto/clusters/attachedDatabaseConfigurations")
    end

end %class

