classdef CheckNameResult < adx.control.JSONMapper
% CheckNameResult The result returned from a check name availability request.
% 
% CheckNameResult Properties:
%   nameAvailable - Specifies a Boolean value that indicates if the name is available. - type: logical
%   name - The name that was checked. - type: string
%   message - Message indicating an unavailable name due to a conflict, or a description of the naming rules that are violated. - type: string
%   reason - Message providing the reason why the given name is invalid. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % nameAvailable - Specifies a Boolean value that indicates if the name is available. - type: logical
        nameAvailable logical { adx.control.JSONMapper.fieldName(nameAvailable,"nameAvailable") }
        % name - The name that was checked. - type: string
        name string { adx.control.JSONMapper.fieldName(name,"name") }
        % message - Message indicating an unavailable name due to a conflict, or a description of the naming rules that are violated. - type: string
        message string { adx.control.JSONMapper.fieldName(message,"message") }
        % reason - Message providing the reason why the given name is invalid. - type: string
        reason adx.control.models.CheckNameResultReasonEnum { adx.control.JSONMapper.fieldName(reason,"reason") }
    end

    % Class methods
    methods
        % Constructor
        function obj = CheckNameResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.CheckNameResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

