classdef Cluster < adx.control.JSONMapper
% Cluster Class representing a Kusto cluster.
% 
% Cluster Properties:
%   sku - type: AzureSku
%   systemData - type: systemData
%   zones - An array represents the availability zones of the cluster. - type: array of string
%   identity - type: Identity
%   xproperties - type: ClusterProperties_1
%   etag - A unique read-only string that changes whenever the resource is updated. - type: string
%   id - Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} - type: string
%   name - The name of the resource - type: string
%   type - The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\" or \"Microsoft.Storage/storageAccounts\" - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % sku - type: AzureSku
        sku adx.control.models.AzureSku { adx.control.JSONMapper.fieldName(sku,"sku") }
        % systemData - type: systemData
        systemData adx.control.models.systemData { adx.control.JSONMapper.fieldName(systemData,"systemData") }
        % zones - An array represents the availability zones of the cluster. - type: array of string
        zones string { adx.control.JSONMapper.fieldName(zones,"zones"), adx.control.JSONMapper.JSONArray }
        % identity - type: Identity
        identity adx.control.models.Identity { adx.control.JSONMapper.fieldName(identity,"identity") }
        % xproperties - type: ClusterProperties_1
        xproperties adx.control.models.ClusterProperties_1 { adx.control.JSONMapper.fieldName(xproperties,"properties") }
        % etag - A unique read-only string that changes whenever the resource is updated. - type: string
        etag string { adx.control.JSONMapper.fieldName(etag,"etag") }
        % id - Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName} - type: string
        id string { adx.control.JSONMapper.fieldName(id,"id") }
        % name - The name of the resource - type: string
        name string { adx.control.JSONMapper.fieldName(name,"name") }
        % type - The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\" or \"Microsoft.Storage/storageAccounts\" - type: string
        type string { adx.control.JSONMapper.fieldName(type,"type") }

        location string {adx.control.JSONMapper.fieldName(location,"location")}
        tags adx.control.JSONMapperMap { adx.control.JSONMapper.fieldName(tags,"tags") }
    end

    % Class methods
    methods
        % Constructor
        function obj = Cluster(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.Cluster
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

