classdef ClusterProperties_1EngineTypeEnum < adx.control.JSONEnum
% ClusterProperties_1EngineTypeEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        V2 ("V2")
        V3 ("V3")
    end

end %class

