classdef ClusterPrincipalProperties_1RoleEnum < adx.control.JSONEnum
% ClusterPrincipalProperties_1RoleEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        AllDatabasesAdmin ("AllDatabasesAdmin")
        AllDatabasesViewer ("AllDatabasesViewer")
    end

end %class

