classdef Compression < adx.control.JSONEnum
% Compression The compression type

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        None ("None")
        GZip ("GZip")
    end

end %class

