classdef CosmosDbDataConnectionProperties_1 < adx.control.JSONMapper
% CosmosDbDataConnectionProperties_1 Class representing the Kusto CosmosDb data connection properties.
% 
% CosmosDbDataConnectionProperties_1 Properties:
%   tableName - The case-sensitive name of the existing target table in your cluster. Retrieved data is ingested into this table. - type: string
%   mappingRuleName - The name of an existing mapping rule to use when ingesting the retrieved data. - type: string
%   managedIdentityResourceId - The resource ID of a managed system or user-assigned identity. The identity is used to authenticate with Cosmos DB. - type: string
%   managedIdentityObjectId - The object ID of the managed identity resource. - type: string
%   cosmosDbAccountResourceId - The resource ID of the Cosmos DB account used to create the data connection. - type: string
%   cosmosDbDatabase - The name of an existing database in the Cosmos DB account. - type: string
%   cosmosDbContainer - The name of an existing container in the Cosmos DB database. - type: string
%   retrievalStartDate - Optional. If defined, the data connection retrieves Cosmos DB documents created or updated after the specified retrieval start date. - type: datetime
%   provisioningState - type: ProvisioningState

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % tableName - The case-sensitive name of the existing target table in your cluster. Retrieved data is ingested into this table. - type: string
        tableName string { adx.control.JSONMapper.fieldName(tableName,"tableName") }
        % mappingRuleName - The name of an existing mapping rule to use when ingesting the retrieved data. - type: string
        mappingRuleName string { adx.control.JSONMapper.fieldName(mappingRuleName,"mappingRuleName") }
        % managedIdentityResourceId - The resource ID of a managed system or user-assigned identity. The identity is used to authenticate with Cosmos DB. - type: string
        managedIdentityResourceId string { adx.control.JSONMapper.fieldName(managedIdentityResourceId,"managedIdentityResourceId") }
        % managedIdentityObjectId - The object ID of the managed identity resource. - type: string
        managedIdentityObjectId string { adx.control.JSONMapper.fieldName(managedIdentityObjectId,"managedIdentityObjectId") }
        % cosmosDbAccountResourceId - The resource ID of the Cosmos DB account used to create the data connection. - type: string
        cosmosDbAccountResourceId string { adx.control.JSONMapper.fieldName(cosmosDbAccountResourceId,"cosmosDbAccountResourceId") }
        % cosmosDbDatabase - The name of an existing database in the Cosmos DB account. - type: string
        cosmosDbDatabase string { adx.control.JSONMapper.fieldName(cosmosDbDatabase,"cosmosDbDatabase") }
        % cosmosDbContainer - The name of an existing container in the Cosmos DB database. - type: string
        cosmosDbContainer string { adx.control.JSONMapper.fieldName(cosmosDbContainer,"cosmosDbContainer") }
        % retrievalStartDate - Optional. If defined, the data connection retrieves Cosmos DB documents created or updated after the specified retrieval start date. - type: datetime
        retrievalStartDate datetime { adx.control.JSONMapper.stringDatetime(retrievalStartDate,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), adx.control.JSONMapper.fieldName(retrievalStartDate,"retrievalStartDate") }
        % provisioningState - type: ProvisioningState
        provisioningState adx.control.models.ProvisioningState { adx.control.JSONMapper.fieldName(provisioningState,"provisioningState") }
    end

    % Class methods
    methods
        % Constructor
        function obj = CosmosDbDataConnectionProperties_1(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.CosmosDbDataConnectionProperties_1
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

