classdef DataConnectionKindEnum < adx.control.JSONEnum
% DataConnectionKindEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        EventHub ("EventHub")
        EventGrid ("EventGrid")
        IotHub ("IotHub")
        CosmosDb ("CosmosDb")
    end

end %class

