classdef DatabaseInviteFollowerResult < adx.control.JSONMapper
% DatabaseInviteFollowerResult The result returned from a follower invitation generation request.
% 
% DatabaseInviteFollowerResult Properties:
%   generatedInvitation - The generated invitation token. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % generatedInvitation - The generated invitation token. - type: string
        generatedInvitation string { adx.control.JSONMapper.fieldName(generatedInvitation,"generatedInvitation") }
    end

    % Class methods
    methods
        % Constructor
        function obj = DatabaseInviteFollowerResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.DatabaseInviteFollowerResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

