classdef DataConnectionCheckNameRequestTypeEnum < adx.control.JSONEnum
% DataConnectionCheckNameRequestTypeEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Microsoft_Kusto_clusters_databases_dataConnections ("Microsoft.Kusto/clusters/databases/dataConnections")
    end

end %class

