classdef DataConnectionValidationListResult < adx.control.JSONMapper
% DataConnectionValidationListResult The list Kusto data connection validation result.
% 
% DataConnectionValidationListResult Properties:
%   value - The list of Kusto data connection validation errors. - type: array of DataConnectionValidationResult

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % value - The list of Kusto data connection validation errors. - type: array of DataConnectionValidationResult
        value adx.control.models.DataConnectionValidationResult { adx.control.JSONMapper.fieldName(value,"value"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = DataConnectionValidationListResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.DataConnectionValidationListResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

