classdef DatabasePrincipalProperties < adx.control.JSONMapper
% DatabasePrincipalProperties A class representing database principal property.
% 
% DatabasePrincipalProperties Properties:
%   principalId - The principal ID assigned to the database principal. It can be a user email, application ID, or security group name. - type: string
%   role - Database principal role. - type: string
%   tenantId - The tenant id of the principal - type: string
%   principalType - Principal type. - type: string
%   tenantName - The tenant name of the principal - type: string
%   principalName - The principal name - type: string
%   provisioningState - type: ProvisioningState
%   aadObjectId - The service principal object id in AAD (Azure active directory) - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % principalId - The principal ID assigned to the database principal. It can be a user email, application ID, or security group name. - type: string
        principalId string { adx.control.JSONMapper.fieldName(principalId,"principalId") }
        % role - Database principal role. - type: string
        role adx.control.models.DatabasePrincipalPropertiesRoleEnum { adx.control.JSONMapper.fieldName(role,"role") }
        % tenantId - The tenant id of the principal - type: string
        tenantId string { adx.control.JSONMapper.fieldName(tenantId,"tenantId") }
        % principalType - Principal type. - type: string
        principalType adx.control.models.DatabasePrincipalPropertiesPrincipalTypeEnum { adx.control.JSONMapper.fieldName(principalType,"principalType") }
        % tenantName - The tenant name of the principal - type: string
        tenantName string { adx.control.JSONMapper.fieldName(tenantName,"tenantName") }
        % principalName - The principal name - type: string
        principalName string { adx.control.JSONMapper.fieldName(principalName,"principalName") }
        % provisioningState - type: ProvisioningState
        provisioningState adx.control.models.ProvisioningState { adx.control.JSONMapper.fieldName(provisioningState,"provisioningState") }
        % aadObjectId - The service principal object id in AAD (Azure active directory) - type: string
        aadObjectId string { adx.control.JSONMapper.fieldName(aadObjectId,"aadObjectId") }
    end

    % Class methods
    methods
        % Constructor
        function obj = DatabasePrincipalProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.DatabasePrincipalProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

