classdef DatabasePrincipalListResult < adx.control.JSONMapper
% DatabasePrincipalListResult The list Kusto database principals operation response.
% 
% DatabasePrincipalListResult Properties:
%   value - The list of Kusto database principals. - type: array of DatabasePrincipal

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % value - The list of Kusto database principals. - type: array of DatabasePrincipal
        value adx.control.models.DatabasePrincipal { adx.control.JSONMapper.fieldName(value,"value"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = DatabasePrincipalListResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.DatabasePrincipalListResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

