classdef DatabaseShareOrigin < adx.control.JSONEnum
% DatabaseShareOrigin The origin of the following setup.

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Direct ("Direct")
        DataShare ("DataShare")
        Other ("Other")
    end

end %class

