classdef DatabaseListResult < adx.control.JSONMapper
% DatabaseListResult The list Kusto databases operation response.
% 
% DatabaseListResult Properties:
%   nextLink - Link to the next page of results - type: string
%   value - The list of Kusto databases. - type: array of Database

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % nextLink - Link to the next page of results - type: string
        nextLink string { adx.control.JSONMapper.fieldName(nextLink,"nextLink") }
        % value - The list of Kusto databases. - type: array of Database
        value adx.control.models.Database { adx.control.JSONMapper.fieldName(value,"value"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = DatabaseListResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.DatabaseListResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

