classdef DatabasePrincipalAssignmentListResult < adx.control.JSONMapper
% DatabasePrincipalAssignmentListResult The list Kusto database principal assignments operation response.
% 
% DatabasePrincipalAssignmentListResult Properties:
%   value - The list of Kusto database principal assignments. - type: array of DatabasePrincipalAssignment

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % value - The list of Kusto database principal assignments. - type: array of DatabasePrincipalAssignment
        value adx.control.models.DatabasePrincipalAssignment { adx.control.JSONMapper.fieldName(value,"value"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = DatabasePrincipalAssignmentListResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.DatabasePrincipalAssignmentListResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

