classdef ErrorDetail < adx.control.JSONMapper
% ErrorDetail The error detail.
% 
% ErrorDetail Properties:
%   code - The error code. - type: string
%   message - The error message. - type: string
%   target - The error target. - type: string
%   details - The error details. - type: array of ErrorDetail
%   additionalInfo - The error additional info. - type: array of ErrorAdditionalInfo

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % code - The error code. - type: string
        code string { adx.control.JSONMapper.fieldName(code,"code") }
        % message - The error message. - type: string
        message string { adx.control.JSONMapper.fieldName(message,"message") }
        % target - The error target. - type: string
        target string { adx.control.JSONMapper.fieldName(target,"target") }
        % details - The error details. - type: array of ErrorDetail
        details adx.control.models.ErrorDetail { adx.control.JSONMapper.fieldName(details,"details"), adx.control.JSONMapper.JSONArray }
        % additionalInfo - The error additional info. - type: array of ErrorAdditionalInfo
        additionalInfo adx.control.models.ErrorAdditionalInfo { adx.control.JSONMapper.fieldName(additionalInfo,"additionalInfo"), adx.control.JSONMapper.JSONArray }
        % Error context data, can be returned by query - (Manually Added)
        context { adx.control.JSONMapper.fieldName(context,"@context") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ErrorDetail(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.ErrorDetail
            end
            obj@adx.control.JSONMapper(s,inputs);
        end

        function disp(obj, options)
            arguments
                obj (1,1) adx.control.models.ErrorDetail
                options.prefix string {mustBeTextScalar} = ""
            end
            mathworks.internal.adx.dispErrorDetails(obj, prefix=options.prefix);
        end
    end %methods
end %class

