classdef ErrorResponse < adx.control.JSONMapper
% ErrorResponse Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.).
% 
% ErrorResponse Properties:
%   error - type: ErrorDetail

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % error - type: ErrorDetail
        error adx.control.models.ErrorDetail { adx.control.JSONMapper.fieldName(error,"error") }
    end

    % Class methods
    methods
        % Constructor
        function obj = ErrorResponse(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.ErrorResponse
            end
            obj@adx.control.JSONMapper(s,inputs);
        end

        function disp(obj, options)
            arguments
                obj (1,1) adx.control.models.ErrorResponse
                options.prefix string {mustBeTextScalar} = ""
            end
            mathworks.internal.adx.dispErrorResponse(obj, prefix=options.prefix);
        end
    end %methods
end %class

