classdef EventHubConnectionProperties_1DatabaseRoutingEnum < adx.control.JSONEnum
% EventHubConnectionProperties_1DatabaseRoutingEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Single ("Single")
        Multi ("Multi")
    end

end %class

