classdef EventGridConnectionProperties < adx.control.JSONMapper
% EventGridConnectionProperties Class representing the Kusto event grid connection properties.
% 
% EventGridConnectionProperties Properties:
%   storageAccountResourceId - The resource ID of the storage account where the data resides. - type: string
%   eventGridResourceId - The resource ID of the event grid that is subscribed to the storage account events. - type: string
%   eventHubResourceId - The resource ID where the event grid is configured to send events. - type: string
%   consumerGroup - The event hub consumer group. - type: string
%   tableName - The table where the data should be ingested. Optionally the table information can be added to each message. - type: string
%   mappingRuleName - The mapping rule to be used to ingest the data. Optionally the mapping information can be added to each message. - type: string
%   dataFormat - type: EventGridDataFormat
%   ignoreFirstRecord - A Boolean value that, if set to true, indicates that ingestion should ignore the first record of every file - type: logical
%   blobStorageEventType - type: BlobStorageEventType
%   managedIdentityResourceId - The resource ID of a managed identity (system or user assigned) to be used to authenticate with event hub and storage account. - type: string
%   managedIdentityObjectId - The object ID of managedIdentityResourceId - type: string
%   databaseRouting - Indication for database routing information from the data connection, by default only database routing information is allowed - type: string
%   provisioningState - type: ProvisioningState

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % storageAccountResourceId - The resource ID of the storage account where the data resides. - type: string
        storageAccountResourceId string { adx.control.JSONMapper.fieldName(storageAccountResourceId,"storageAccountResourceId") }
        % eventGridResourceId - The resource ID of the event grid that is subscribed to the storage account events. - type: string
        eventGridResourceId string { adx.control.JSONMapper.fieldName(eventGridResourceId,"eventGridResourceId") }
        % eventHubResourceId - The resource ID where the event grid is configured to send events. - type: string
        eventHubResourceId string { adx.control.JSONMapper.fieldName(eventHubResourceId,"eventHubResourceId") }
        % consumerGroup - The event hub consumer group. - type: string
        consumerGroup string { adx.control.JSONMapper.fieldName(consumerGroup,"consumerGroup") }
        % tableName - The table where the data should be ingested. Optionally the table information can be added to each message. - type: string
        tableName string { adx.control.JSONMapper.fieldName(tableName,"tableName") }
        % mappingRuleName - The mapping rule to be used to ingest the data. Optionally the mapping information can be added to each message. - type: string
        mappingRuleName string { adx.control.JSONMapper.fieldName(mappingRuleName,"mappingRuleName") }
        % dataFormat - type: EventGridDataFormat
        dataFormat adx.control.models.EventGridDataFormat { adx.control.JSONMapper.fieldName(dataFormat,"dataFormat") }
        % ignoreFirstRecord - A Boolean value that, if set to true, indicates that ingestion should ignore the first record of every file - type: logical
        ignoreFirstRecord logical { adx.control.JSONMapper.fieldName(ignoreFirstRecord,"ignoreFirstRecord") }
        % blobStorageEventType - type: BlobStorageEventType
        blobStorageEventType adx.control.models.BlobStorageEventType { adx.control.JSONMapper.fieldName(blobStorageEventType,"blobStorageEventType") }
        % managedIdentityResourceId - The resource ID of a managed identity (system or user assigned) to be used to authenticate with event hub and storage account. - type: string
        managedIdentityResourceId string { adx.control.JSONMapper.fieldName(managedIdentityResourceId,"managedIdentityResourceId") }
        % managedIdentityObjectId - The object ID of managedIdentityResourceId - type: string
        managedIdentityObjectId string { adx.control.JSONMapper.fieldName(managedIdentityObjectId,"managedIdentityObjectId") }
        % databaseRouting - Indication for database routing information from the data connection, by default only database routing information is allowed - type: string
        databaseRouting adx.control.models.EventGridConnectionPropertiesDatabaseRoutingEnum { adx.control.JSONMapper.fieldName(databaseRouting,"databaseRouting") }
        % provisioningState - type: ProvisioningState
        provisioningState adx.control.models.ProvisioningState { adx.control.JSONMapper.fieldName(provisioningState,"provisioningState") }
    end

    % Class methods
    methods
        % Constructor
        function obj = EventGridConnectionProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.EventGridConnectionProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

