classdef FollowerDatabaseDefinition < adx.control.JSONMapper
% FollowerDatabaseDefinition A class representing follower database request.
% 
% FollowerDatabaseDefinition Properties:
%   clusterResourceId - Resource id of the cluster that follows a database owned by this cluster. - type: string
%   attachedDatabaseConfigurationName - Resource name of the attached database configuration in the follower cluster. - type: string
%   databaseName - The database name owned by this cluster that was followed. * in case following all databases. - type: string
%   tableLevelSharingProperties - type: TableLevelSharingProperties
%   databaseShareOrigin - type: DatabaseShareOrigin

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % clusterResourceId - Resource id of the cluster that follows a database owned by this cluster. - type: string
        clusterResourceId string { adx.control.JSONMapper.fieldName(clusterResourceId,"clusterResourceId") }
        % attachedDatabaseConfigurationName - Resource name of the attached database configuration in the follower cluster. - type: string
        attachedDatabaseConfigurationName string { adx.control.JSONMapper.fieldName(attachedDatabaseConfigurationName,"attachedDatabaseConfigurationName") }
        % databaseName - The database name owned by this cluster that was followed. * in case following all databases. - type: string
        databaseName string { adx.control.JSONMapper.fieldName(databaseName,"databaseName") }
        % tableLevelSharingProperties - type: TableLevelSharingProperties
        tableLevelSharingProperties  { adx.control.JSONMapper.fieldName(tableLevelSharingProperties,"tableLevelSharingProperties") }
        % databaseShareOrigin - type: DatabaseShareOrigin
        databaseShareOrigin adx.control.models.DatabaseShareOrigin { adx.control.JSONMapper.fieldName(databaseShareOrigin,"databaseShareOrigin") }
    end

    % Class methods
    methods
        % Constructor
        function obj = FollowerDatabaseDefinition(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.FollowerDatabaseDefinition
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

