classdef IdentityTypeEnum < adx.control.JSONEnum
% IdentityTypeEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        None ("None")
        SystemAssigned ("SystemAssigned")
        UserAssigned ("UserAssigned")
        SystemAssigned_UserAssigned ("SystemAssigned, UserAssigned")
    end

end %class

