classdef KeyVaultProperties < adx.control.JSONMapper
% KeyVaultProperties Properties of the key vault.
% 
% KeyVaultProperties Properties:
%   keyName - The name of the key vault key. - type: string
%   keyVersion - The version of the key vault key. - type: string
%   keyVaultUri - The Uri of the key vault. - type: string
%   userIdentity - The user assigned identity (ARM resource id) that has access to the key. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % keyName - The name of the key vault key. - type: string
        keyName string { adx.control.JSONMapper.fieldName(keyName,"keyName") }
        % keyVersion - The version of the key vault key. - type: string
        keyVersion string { adx.control.JSONMapper.fieldName(keyVersion,"keyVersion") }
        % keyVaultUri - The Uri of the key vault. - type: string
        keyVaultUri string { adx.control.JSONMapper.fieldName(keyVaultUri,"keyVaultUri") }
        % userIdentity - The user assigned identity (ARM resource id) that has access to the key. - type: string
        userIdentity string { adx.control.JSONMapper.fieldName(userIdentity,"userIdentity") }
    end

    % Class methods
    methods
        % Constructor
        function obj = KeyVaultProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.KeyVaultProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

