classdef LanguageExtension < adx.control.JSONMapper
% LanguageExtension The language extension object.
% 
% LanguageExtension Properties:
%   languageExtensionName - type: LanguageExtensionName
%   languageExtensionImageName - type: LanguageExtensionImageName

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % languageExtensionName - type: LanguageExtensionName
        languageExtensionName adx.control.models.LanguageExtensionName { adx.control.JSONMapper.fieldName(languageExtensionName,"languageExtensionName") }
        % languageExtensionImageName - type: LanguageExtensionImageName
        languageExtensionImageName adx.control.models.LanguageExtensionImageName { adx.control.JSONMapper.fieldName(languageExtensionImageName,"languageExtensionImageName") }
    end

    % Class methods
    methods
        % Constructor
        function obj = LanguageExtension(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.LanguageExtension
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

