classdef LanguageExtensionName < adx.control.JSONEnum
% LanguageExtensionName Language extension that can run within KQL query.

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        PYTHON ("PYTHON")
        R ("R")
    end

end %class

