classdef ListResourceSkusResult < adx.control.JSONMapper
% ListResourceSkusResult List of available SKUs for a Kusto Cluster.
% 
% ListResourceSkusResult Properties:
%   value - The collection of available SKUs for an existing resource. - type: array of AzureResourceSku_1

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % value - The collection of available SKUs for an existing resource. - type: array of AzureResourceSku_1
        value adx.control.models.AzureResourceSku_1 { adx.control.JSONMapper.fieldName(value,"value"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = ListResourceSkusResult(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.ListResourceSkusResult
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

