classdef MigrationClusterPropertiesRoleEnum < adx.control.JSONEnum
% MigrationClusterPropertiesRoleEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Source ("Source")
        Destination ("Destination")
    end

end %class

