classdef OperationResultProperties < adx.control.JSONMapper
% OperationResultProperties Operation result properties
% 
% OperationResultProperties Properties:
%   operationKind - The kind of the operation. - type: string
%   provisioningState - type: ProvisioningState
%   operationState - The state of the operation. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % operationKind - The kind of the operation. - type: string
        operationKind string { adx.control.JSONMapper.fieldName(operationKind,"operationKind") }
        % provisioningState - type: ProvisioningState
        provisioningState adx.control.models.ProvisioningState { adx.control.JSONMapper.fieldName(provisioningState,"provisioningState") }
        % operationState - The state of the operation. - type: string
        operationState string { adx.control.JSONMapper.fieldName(operationState,"operationState") }
    end

    % Class methods
    methods
        % Constructor
        function obj = OperationResultProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.OperationResultProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

