classdef OperationResultErrorProperties < adx.control.JSONMapper
% OperationResultErrorProperties Operation result error properties
% 
% OperationResultErrorProperties Properties:
%   code - The code of the error. - type: string
%   message - The error message. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % code - The code of the error. - type: string
        code string { adx.control.JSONMapper.fieldName(code,"code") }
        % message - The error message. - type: string
        message string { adx.control.JSONMapper.fieldName(message,"message") }
    end

    % Class methods
    methods
        % Constructor
        function obj = OperationResultErrorProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.OperationResultErrorProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

