classdef OptimizedAutoscale < adx.control.JSONMapper
% OptimizedAutoscale A class that contains the optimized auto scale definition.
% 
% OptimizedAutoscale Properties:
%   version - The version of the template defined, for instance 1. - type: int32
%   isEnabled - A boolean value that indicate if the optimized autoscale feature is enabled or not. - type: logical
%   minimum - Minimum allowed instances count. - type: int32
%   maximum - Maximum allowed instances count. - type: int32

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % version - The version of the template defined, for instance 1. - type: int32
        version int32 { adx.control.JSONMapper.fieldName(version,"version") }
        % isEnabled - A boolean value that indicate if the optimized autoscale feature is enabled or not. - type: logical
        isEnabled logical { adx.control.JSONMapper.fieldName(isEnabled,"isEnabled") }
        % minimum - Minimum allowed instances count. - type: int32
        minimum int32 { adx.control.JSONMapper.fieldName(minimum,"minimum") }
        % maximum - Maximum allowed instances count. - type: int32
        maximum int32 { adx.control.JSONMapper.fieldName(maximum,"maximum") }
    end

    % Class methods
    methods
        % Constructor
        function obj = OptimizedAutoscale(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.OptimizedAutoscale
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

