classdef PrivateEndpointConnectionProperties < adx.control.JSONMapper
% PrivateEndpointConnectionProperties Properties of a private endpoint connection.
% 
% PrivateEndpointConnectionProperties Properties:
%   privateEndpoint - type: PrivateEndpointProperty
%   privateLinkServiceConnectionState - type: PrivateLinkServiceConnectionStateProperty
%   groupId - Group id of the private endpoint. - type: string
%   provisioningState - Provisioning state of the private endpoint. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % privateEndpoint - type: PrivateEndpointProperty
        privateEndpoint adx.control.models.PrivateEndpointProperty { adx.control.JSONMapper.fieldName(privateEndpoint,"privateEndpoint") }
        % privateLinkServiceConnectionState - type: PrivateLinkServiceConnectionStateProperty
        privateLinkServiceConnectionState adx.control.models.PrivateLinkServiceConnectionStateProperty { adx.control.JSONMapper.fieldName(privateLinkServiceConnectionState,"privateLinkServiceConnectionState") }
        % groupId - Group id of the private endpoint. - type: string
        groupId string { adx.control.JSONMapper.fieldName(groupId,"groupId") }
        % provisioningState - Provisioning state of the private endpoint. - type: string
        provisioningState string { adx.control.JSONMapper.fieldName(provisioningState,"provisioningState") }
    end

    % Class methods
    methods
        % Constructor
        function obj = PrivateEndpointConnectionProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.PrivateEndpointConnectionProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

