classdef PrivateEndpointProperty < adx.control.JSONMapper
% PrivateEndpointProperty Private endpoint which the connection belongs to.
% 
% PrivateEndpointProperty Properties:
%   id - Resource id of the private endpoint. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % id - Resource id of the private endpoint. - type: string
        id string { adx.control.JSONMapper.fieldName(id,"id") }
    end

    % Class methods
    methods
        % Constructor
        function obj = PrivateEndpointProperty(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.PrivateEndpointProperty
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

