classdef ResourceSkuZoneDetails < adx.control.JSONMapper
% ResourceSkuZoneDetails Describes The zonal capabilities of a SKU.
% 
% ResourceSkuZoneDetails Properties:
%   name - The set of zones that the SKU is available in with the specified capabilities. - type: array of string
%   capabilities - A list of capabilities that are available for the SKU in the specified list of zones. - type: array of ResourceSkuCapabilities

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % name - The set of zones that the SKU is available in with the specified capabilities. - type: array of string
        name string { adx.control.JSONMapper.fieldName(name,"name"), adx.control.JSONMapper.JSONArray }
        % capabilities - A list of capabilities that are available for the SKU in the specified list of zones. - type: array of ResourceSkuCapabilities
        capabilities adx.control.models.ResourceSkuCapabilities { adx.control.JSONMapper.fieldName(capabilities,"capabilities"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = ResourceSkuZoneDetails(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.ResourceSkuZoneDetails
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

