classdef Status < adx.control.JSONEnum
% Status The status of operation.

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        Succeeded ("Succeeded")
        Canceled ("Canceled")
        Failed ("Failed")
        Running ("Running")
    end

end %class

