classdef systemDataCreatedByTypeEnum < adx.control.JSONEnum
% systemDataCreatedByTypeEnum No description provided

    % This file is automatically generated using OpenAPI
    % Specification version: 2023-05-02
    % MATLAB Generator for OpenAPI version: 1.0.0
    % (c) 2023 MathWorks Inc.

    enumeration 
        User ("User")
        Application ("Application")
        ManagedIdentity ("ManagedIdentity")
        Key ("Key")
    end

end %class

