classdef systemData < adx.control.JSONMapper
% systemData Metadata pertaining to creation and last modification of the resource.
% 
% systemData Properties:
%   createdBy - The identity that created the resource. - type: string
%   createdByType - The type of identity that created the resource. - type: string
%   createdAt - The timestamp of resource creation (UTC). - type: datetime
%   lastModifiedBy - The identity that last modified the resource. - type: string
%   lastModifiedByType - The type of identity that last modified the resource. - type: string
%   lastModifiedAt - The timestamp of resource last modification (UTC) - type: datetime

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % createdBy - The identity that created the resource. - type: string
        createdBy string { adx.control.JSONMapper.fieldName(createdBy,"createdBy") }
        % createdByType - The type of identity that created the resource. - type: string
        createdByType adx.control.models.systemDataCreatedByTypeEnum { adx.control.JSONMapper.fieldName(createdByType,"createdByType") }
        % createdAt - The timestamp of resource creation (UTC). - type: datetime
        createdAt datetime { adx.control.JSONMapper.stringDatetime(createdAt,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), adx.control.JSONMapper.fieldName(createdAt,"createdAt") }
        % lastModifiedBy - The identity that last modified the resource. - type: string
        lastModifiedBy string { adx.control.JSONMapper.fieldName(lastModifiedBy,"lastModifiedBy") }
        % lastModifiedByType - The type of identity that last modified the resource. - type: string
        lastModifiedByType adx.control.models.systemDataLastModifiedByTypeEnum { adx.control.JSONMapper.fieldName(lastModifiedByType,"lastModifiedByType") }
        % lastModifiedAt - The timestamp of resource last modification (UTC) - type: datetime
        lastModifiedAt datetime { adx.control.JSONMapper.stringDatetime(lastModifiedAt,'yyyy-MM-dd''T''HH:mm:ss.SSSZ', 'TimeZone', 'local'), adx.control.JSONMapper.fieldName(lastModifiedAt,"lastModifiedAt") }
    end

    % Class methods
    methods
        % Constructor
        function obj = systemData(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.systemData
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

