classdef TableLevelSharingProperties < adx.control.JSONMapper
% TableLevelSharingProperties Tables that will be included and excluded in the follower database
% 
% TableLevelSharingProperties Properties:
%   tablesToInclude - List of tables to include in the follower database - type: array of string
%   tablesToExclude - List of tables to exclude from the follower database - type: array of string
%   externalTablesToInclude - List of external tables to include in the follower database - type: array of string
%   externalTablesToExclude - List of external tables to exclude from the follower database - type: array of string
%   materializedViewsToInclude - List of materialized views to include in the follower database - type: array of string
%   materializedViewsToExclude - List of materialized views to exclude from the follower database - type: array of string
%   functionsToInclude - List of functions to include in the follower database - type: array of string
%   functionsToExclude - List of functions to exclude from the follower database - type: array of string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % tablesToInclude - List of tables to include in the follower database - type: array of string
        tablesToInclude string { adx.control.JSONMapper.fieldName(tablesToInclude,"tablesToInclude"), adx.control.JSONMapper.JSONArray }
        % tablesToExclude - List of tables to exclude from the follower database - type: array of string
        tablesToExclude string { adx.control.JSONMapper.fieldName(tablesToExclude,"tablesToExclude"), adx.control.JSONMapper.JSONArray }
        % externalTablesToInclude - List of external tables to include in the follower database - type: array of string
        externalTablesToInclude string { adx.control.JSONMapper.fieldName(externalTablesToInclude,"externalTablesToInclude"), adx.control.JSONMapper.JSONArray }
        % externalTablesToExclude - List of external tables to exclude from the follower database - type: array of string
        externalTablesToExclude string { adx.control.JSONMapper.fieldName(externalTablesToExclude,"externalTablesToExclude"), adx.control.JSONMapper.JSONArray }
        % materializedViewsToInclude - List of materialized views to include in the follower database - type: array of string
        materializedViewsToInclude string { adx.control.JSONMapper.fieldName(materializedViewsToInclude,"materializedViewsToInclude"), adx.control.JSONMapper.JSONArray }
        % materializedViewsToExclude - List of materialized views to exclude from the follower database - type: array of string
        materializedViewsToExclude string { adx.control.JSONMapper.fieldName(materializedViewsToExclude,"materializedViewsToExclude"), adx.control.JSONMapper.JSONArray }
        % functionsToInclude - List of functions to include in the follower database - type: array of string
        functionsToInclude string { adx.control.JSONMapper.fieldName(functionsToInclude,"functionsToInclude"), adx.control.JSONMapper.JSONArray }
        % functionsToExclude - List of functions to exclude from the follower database - type: array of string
        functionsToExclude string { adx.control.JSONMapper.fieldName(functionsToExclude,"functionsToExclude"), adx.control.JSONMapper.JSONArray }
    end

    % Class methods
    methods
        % Constructor
        function obj = TableLevelSharingProperties(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.TableLevelSharingProperties
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

