classdef The_object_that_describes_the_operation_ < adx.control.JSONMapper
% The_object_that_describes_the_operation_ No description provided
% 
% The_object_that_describes_the_operation_ Properties:
%   provider - type: string
%   operation - For example: read, write, delete. - type: string
%   resource - type: string
%   description - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % provider - type: string
        provider string { adx.control.JSONMapper.fieldName(provider,"provider") }
        % operation - For example: read, write, delete. - type: string
        operation string { adx.control.JSONMapper.fieldName(operation,"operation") }
        % resource - type: string
        resource string { adx.control.JSONMapper.fieldName(resource,"resource") }
        % description - type: string
        description string { adx.control.JSONMapper.fieldName(description,"description") }
    end

    % Class methods
    methods
        % Constructor
        function obj = The_object_that_describes_the_operation_(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.The_object_that_describes_the_operation_
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

