classdef VirtualNetworkConfiguration < adx.control.JSONMapper
% VirtualNetworkConfiguration A class that contains virtual network definition.
% 
% VirtualNetworkConfiguration Properties:
%   subnetId - The subnet resource id. - type: string
%   enginePublicIpId - Engine service''s public IP address resource id. - type: string
%   dataManagementPublicIpId - Data management''s service public IP address resource id. - type: string

% This file is automatically generated using OpenAPI
% Specification version: 2023-05-02
% MATLAB Generator for OpenAPI version: 1.0.0
% (c) 2023 MathWorks Inc.

    % Class properties
    properties
        % subnetId - The subnet resource id. - type: string
        subnetId string { adx.control.JSONMapper.fieldName(subnetId,"subnetId") }
        % enginePublicIpId - Engine service''s public IP address resource id. - type: string
        enginePublicIpId string { adx.control.JSONMapper.fieldName(enginePublicIpId,"enginePublicIpId") }
        % dataManagementPublicIpId - Data management''s service public IP address resource id. - type: string
        dataManagementPublicIpId string { adx.control.JSONMapper.fieldName(dataManagementPublicIpId,"dataManagementPublicIpId") }
    end

    % Class methods
    methods
        % Constructor
        function obj = VirtualNetworkConfiguration(s,inputs)
            % To allow proper nesting of object, derived objects must
            % call the JSONMapper constructor from their constructor. This 
            % also allows objects to be instantiated with Name-Value pairs
            % as inputs to set properties to specified values.
            arguments
                s { adx.control.JSONMapper.ConstructorArgument } = []
                inputs.?adx.control.models.VirtualNetworkConfiguration
            end
            obj@adx.control.JSONMapper(s,inputs);
        end
    end %methods
end %class

