classdef testMapTypesMATLABToKusto < matlab.unittest.TestCase
    % testMapTypesMATLABToKusto Unit testing for MATLAB to Kusto type mapping

    %  (c) 2026 MathWorks, Inc.

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %% Please add your test cases below
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    properties (TestParameter)
        supportedMappingCase = struct( ...
            'int32Type', struct('inputType', "int32", 'expectedType', "int"), ...
            'int8Type', struct('inputType', "int8", 'expectedType', "int"), ...
            'uint8Type', struct('inputType', "uint8", 'expectedType', "int"), ...
            'int16Type', struct('inputType', "int16", 'expectedType', "int"), ...
            'uint16Type', struct('inputType', "uint16", 'expectedType', "int"), ...
            'int64Type', struct('inputType', "int64", 'expectedType', "long"), ...
            'uint32Type', struct('inputType', "uint32", 'expectedType', "long"), ...
            'stringType', struct('inputType', "string", 'expectedType', "string"), ...
            'charType', struct('inputType', "char", 'expectedType', "string"), ...
            'doubleType', struct('inputType', "double", 'expectedType', "real"), ...
            'singleType', struct('inputType', "single", 'expectedType', "real"), ...
            'datetimeType', struct('inputType', "datetime", 'expectedType', "datetime"), ...
            'durationType', struct('inputType', "duration", 'expectedType', "timespan"), ...
            'logicalType', struct('inputType', "logical", 'expectedType', "bool"), ...
            'charVectorInput', struct('inputType', 'double', 'expectedType', "real"));
        caseInsensitiveCase = struct( ...
            'mixedCaseInt32', struct('inputType', "Int32", 'expectedType', "int"), ...
            'mixedCaseUint32', struct('inputType', "UiNt32", 'expectedType', "long"), ...
            'mixedCaseDatetime', struct('inputType', "DateTime", 'expectedType', "datetime"), ...
            'mixedCaseLogical', struct('inputType', "LoGiCaL", 'expectedType', "bool"));
    end

    methods (TestClassSetup)
    end

    methods (TestMethodSetup)
        function testSetup(testCase) %#ok<MANU>
        end
    end

    methods (TestMethodTeardown)
        function testTearDown(testCase) %#ok<MANU>
        end
    end

    methods (Test)
        function testSupportedTypeMappings(testCase, supportedMappingCase)
            actualType = mathworks.internal.adx.mapTypesMATLABToKusto( ...
                supportedMappingCase.inputType);

            testCase.verifyEqual(actualType, supportedMappingCase.expectedType);
        end

        function testTypeMappingsAreCaseInsensitive(testCase, caseInsensitiveCase)
            actualType = mathworks.internal.adx.mapTypesMATLABToKusto( ...
                caseInsensitiveCase.inputType);

            testCase.verifyEqual(actualType, caseInsensitiveCase.expectedType);
        end

        function testUnsupportedTypeWarnsAndFallsBackToString(testCase)
            actualType = testCase.verifyWarning( ...
                @() mathworks.internal.adx.mapTypesMATLABToKusto("uint64"), ...
                "adx:mapTypesMATLABToKusto:Unsupported");

            testCase.verifyEqual(actualType, "string");
        end

        function testRejectsEmptyStringInput(testCase)
            testCase.verifyError( ...
                @() mathworks.internal.adx.mapTypesMATLABToKusto(""), ...
                "MATLAB:validators:mustBeNonzeroLengthText");
        end

        function testRejectsNonScalarStringInput(testCase)
            testCase.verifyError( ...
                @() mathworks.internal.adx.mapTypesMATLABToKusto(["double", "single"]), ...
                "MATLAB:validators:mustBeTextScalar");
        end
    end
end
